name: Cronus Infrastructure CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: true

  ARM_CLIENT_ID: ${{ vars.AZURE_PLAN_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:
  generate-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod/

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Terraform format
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: |
          terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -no-color